### ISSUE TITLE
the results for cifar10 and cifar100

### ISSUE THREAD

**Issue by Adasunnylily** [Trustworthy-ML-Lab/Label-free-CBM#3]
hi, I use the command in train_command.txt to reproduce, but I got results far more than results in the paper, I am wondering is there any mistake, could you please provide the parameters you used to reproduce results in the paper?
Here are my results with comparison to paper in cifar100
<html>
<body>
<html xmlns:x="tencent"> <body>

paper-standard-sparse | cifar100 | 58.34
-- | -- | --
my-standard-sparse | cifar100 | 73.68
paper-LFCBM | cifar100 | 65.13(65-65,24)
my-LFCBM | cifar100 | 77.34

</body></html>
</body>
</html>

MANY THANKS!!!

**Comment by tuomaso** [comment]
Interesting, what training command did you use? `training_commands.txt` has all the training commands to reproduce our results assuming you haven't changed the default values in the code.

**Comment by Adasunnylily** [comment]
AHhhh, I found that I made a mistake by using VITB-16 as the backbone instead of RN50, now I can reproduce the correct results. Thanks a lot!
