### ISSUE TITLE
[test acc -1.0000]

### ISSUE THREAD

**Issue by renos** [Trustworthy-ML-Lab/Label-free-CBM#5]
When I run cifar 10 / cifar 100 I get [test acc -1.0000] when I run python train_cbm.py --concept_set data/concept_sets/cifar10_filtered.txt

**Comment by ChoiDae1** [comment]
Hi! I also face this issue. It is okay?

**Comment by tuomaso** [comment]
This is not an issue it just means test data was not provided to glm-saga. Val acc is the accuracy of the method on the unseen data.
